/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package UAS_PBO;

import javax.swing.JOptionPane;
import java.sql.*;

/**
 *
 * @author HarryHarkespan
 */
public class Hotel extends javax.swing.JFrame {
    static final String JDBC_DRIVER = "com.mysql.cj.jdbc.Driver";
    static final String DB_URL = "jdbc:mysql://127.0.0.1/test";
    static final String USER = "root";
    static final String PASS = "";
    
    static Connection conn;
    static Statement stmt;
    static ResultSet rs;
    /**
     * Creates new form barang
     */
    public Hotel() {
        
        initComponents();
        pilihan();
        txtHarga.setEditable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator1 = new javax.swing.JSeparator();
        jLabel8 = new javax.swing.JLabel();
        NoKamar = new javax.swing.JComboBox<>();
        CBJenis = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        View = new javax.swing.JButton();
        txtKode = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtNomor = new javax.swing.JTextField();
        txtNama = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        txtHarga = new javax.swing.JTextField();
        Simpan = new javax.swing.JButton();
        Update = new javax.swing.JButton();
        Delete = new javax.swing.JButton();
        Reset = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuKeluar = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel8.setText("ID Kamar");

        CBJenis.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Normal", "Deluxe", "Suite" }));
        CBJenis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CBJenisActionPerformed(evt);
            }
        });

        jLabel9.setText("No");

        View.setText("View");
        View.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewActionPerformed(evt);
            }
        });

        txtKode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtKodeActionPerformed(evt);
            }
        });

        jLabel10.setText("No Kamar");

        jLabel11.setText("Nama");

        jLabel12.setText("Jenis Kamar");

        jLabel15.setText("Harga");

        txtHarga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtHargaActionPerformed(evt);
            }
        });

        Simpan.setText("Simpan");
        Simpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SimpanActionPerformed(evt);
            }
        });

        Update.setText("Update");
        Update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateActionPerformed(evt);
            }
        });

        Delete.setText("Delete");
        Delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteActionPerformed(evt);
            }
        });

        Reset.setText("Reset");
        Reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ResetActionPerformed(evt);
            }
        });

        menuKeluar.setText("Keluar");
        menuKeluar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuKeluarMouseClicked(evt);
            }
        });
        menuKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuKeluarActionPerformed(evt);
            }
        });
        jMenuBar1.add(menuKeluar);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(NoKamar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Simpan)
                                .addGap(18, 18, 18)
                                .addComponent(Update)
                                .addGap(18, 18, 18)
                                .addComponent(Delete)
                                .addGap(18, 18, 18)
                                .addComponent(Reset))
                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                                .addComponent(txtNama, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtNomor, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(CBJenis, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtKode, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtHarga, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(94, 94, 94)
                        .addComponent(View)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(NoKamar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(txtKode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(View)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtNomor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel10)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(txtNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel12)
                    .addComponent(CBJenis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(txtHarga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(99, 99, 99)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Simpan)
                    .addComponent(Update)
                    .addComponent(Delete)
                    .addComponent(Reset))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSimpanActionPerformed
       
    }//GEN-LAST:event_txtSimpanActionPerformed

    
    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        //showtable();
    }//GEN-LAST:event_formWindowOpened

    private void tabelDataMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelDataMouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_tabelDataMouseClicked

    private void tblClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tblClearActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_tblClearActionPerformed

    private void tblUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tblUpdateActionPerformed
        // TODO add your handling code here:
       /* String kode = txtKode.getText().toString().trim();
        String nama = txtNomor.getText();
        
        int stok = Integer.parseInt(txtMasuk.getText());
        int stok_min = Integer.parseInt(txtKeluar.getText());
        update(kode,nama,satuan,stok,stok_min);        
        clear();*/
    }//GEN-LAST:event_tblUpdateActionPerformed

    private void tblDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tblDeleteActionPerformed
        // TODO add your handling code here:     
    }//GEN-LAST:event_tblDeleteActionPerformed

    private void txtKodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtKodeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtKodeActionPerformed

    private void txtNamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNamaActionPerformed

    private void SimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SimpanActionPerformed
        // TODO add your handling code here:
        String kode = txtKode.getText().toString().trim();
        int nomor = Integer.parseInt(txtNomor.getText().trim());
        String nama = txtNama.getText().toString().trim();
        String jenis = CBJenis.getSelectedItem().toString().trim();
        int harga = Integer.parseInt(txtHarga.getText().trim());
        insert(kode,nomor,nama,jenis,harga);
    }//GEN-LAST:event_SimpanActionPerformed

    private void ViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewActionPerformed
        // TODO add your handling code here:
        try {
    int No = Integer.parseInt(NoKamar.getSelectedItem().toString());
    conn = DriverManager.getConnection(DB_URL, USER, PASS);
    
    String sql = "SELECT * FROM uashotel WHERE no_kamar = ?";
    PreparedStatement statement = conn.prepareStatement(sql);
    statement.setInt(1, No);
    
    ResultSet rs = statement.executeQuery();
    
    if (rs.next()) {
        txtKode.setText(rs.getString(1));
        txtNomor.setText(rs.getString(2));
        txtNama.setText(rs.getString(3));
        CBJenis.setSelectedItem(rs.getString(4));
        txtHarga.setText(rs.getString(5));

    }
     Simpan.setEnabled(false);
    conn.close();
} catch (SQLException e) {
    e.printStackTrace();
}
    }//GEN-LAST:event_ViewActionPerformed

    private void UpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateActionPerformed
        // TODO add your handling code here:
        Date currentDate = new Date(System.currentTimeMillis());
       int No = Integer.parseInt(NoKamar.getSelectedItem().toString());
       try {
           String kode = txtKode.getText();
           int nomor = Integer.parseInt(txtNomor.getText().trim());
           String nama = txtNama.getText();
           String jenis = CBJenis.getSelectedItem().toString().trim();
           int harga = Integer.parseInt(txtHarga.getText().trim());          
        Class.forName(JDBC_DRIVER);
        conn = DriverManager.getConnection(DB_URL, USER, PASS);     
        stmt = conn.createStatement();

        // Operasi db
        //String checkSql = "SELECT * FROM barang WHERE id = ?";
        String sql = "UPDATE uashotel set kode_kamar=?, no_kamar= ?, nama= ?, jenis = ?, harga= ? WHERE no_kamar=?";
        PreparedStatement ps = conn.prepareStatement(sql);
        //PreparedStatement psc = conn.prepareStatement(checkSql);
        //psc.setInt(1, id);        "UPDATE uashotel set kode_kamar=?, nama= ?, jenis = ?, tanggal_masuk = ?, tanggal_keluar=? WHERE no_kamar=?";
        ps.setString(1, kode);
        ps.setInt(2, nomor);
        ps.setString(3, nama);
        ps.setString(4, jenis);
        ps.setInt(5, harga);        
        ps.setInt(6,No );

        int x = ps.executeUpdate();
        
        if (x==1)
        {
            JOptionPane.showMessageDialog(this,"Data berhasil diupdate");
            txtKode.setText("");
            txtNomor.setText("");
            txtNama.setText("");
            CBJenis.setSelectedItem("");
            txtHarga.setText("");            
            txtKode.requestFocus();
        }else
        {
            JOptionPane.showMessageDialog(this,"Data Gagal diupdate!");
        }
        

        stmt.close();
        conn.close();
    } catch (Exception e) {
        e.printStackTrace();
    }
    }//GEN-LAST:event_UpdateActionPerformed

    private void DeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteActionPerformed
       
       try {
        int No = Integer.parseInt(NoKamar.getSelectedItem().toString());           
        Class.forName(JDBC_DRIVER);
        conn = DriverManager.getConnection(DB_URL, USER, PASS);     
        stmt = conn.createStatement();

        // Operasi db
        //String checkSql = "SELECT * FROM barang WHERE id = ?";
        String sql = "Delete from uashotel where no_kamar=?";
        PreparedStatement ps = conn.prepareStatement(sql);
        //PreparedStatement psc = conn.prepareStatement(checkSql);
        //psc.setInt(1, id);                
        ps.setInt(1,No );

        int x = ps.executeUpdate();
        
        if (x==1)
        {
            JOptionPane.showMessageDialog(this,"Data Berhasil Dihapus");
            txtKode.setText("");
            txtNomor.setText("");
            txtNama.setText("");
            CBJenis.setSelectedItem("");
            txtHarga.setText("0");                        
            txtKode.requestFocus();
        }else
        {
            JOptionPane.showMessageDialog(this,"Data Gagal Dihapus");
        }
        stmt.close();
        conn.close();
    } catch (Exception e) {        
        e.printStackTrace();
    }
    }//GEN-LAST:event_DeleteActionPerformed

    private void ResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ResetActionPerformed
        // TODO add your handling code here:
        Simpan.setEnabled(true);
        txtKode.setText("");
        txtNomor.setText("");
        txtNama.setText("");
        CBJenis.setSelectedItem("");
        txtHarga.setText("0");        
        NoKamar.setSelectedIndex(0);
    }//GEN-LAST:event_ResetActionPerformed

    private void CBJenisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CBJenisActionPerformed
        // TODO add your handling code here:
        int harga = 0;        
        String selectedOption = (String) CBJenis.getSelectedItem();
                if (selectedOption.equals("Normal")) {                    
                    harga = 500000;
                } else if (selectedOption.equals("Deluxe")) {                    
                    harga = 1000000;
                } else if (selectedOption.equals("Suite")) {                    
                    harga = 1500000;
                }            
                txtHarga.setText(Integer.toString(harga));
    }//GEN-LAST:event_CBJenisActionPerformed

    private void txtHargaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtHargaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtHargaActionPerformed

    private void menuKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuKeluarActionPerformed
        // TODO add your handling code here:
         
    }//GEN-LAST:event_menuKeluarActionPerformed

    private void menuKeluarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuKeluarMouseClicked
        // TODO add your handling code here:
        dispose(); 
    }//GEN-LAST:event_menuKeluarMouseClicked
private void pilihan()
    {
        try {
            conn = DriverManager.getConnection(DB_URL, USER, PASS);
            stmt = conn.createStatement();
            rs = stmt.executeQuery("SELECT no_kamar FROM uashotel");
            while(rs.next())
            {
                NoKamar.addItem(rs.getString(1).toString());
            }
            
            stmt.close();
            conn.close();
            rs.close();
        } catch (SQLException e) {
            e.printStackTrace();
            
        }
    }
public void insert(String kode, int nomor,String nama, String jenis,int harga) {
    Date currentDate = new Date(System.currentTimeMillis());
    try {
        Class.forName(JDBC_DRIVER);
        conn = DriverManager.getConnection(DB_URL, USER, PASS);

        // Pengecekan kd_brg
        String checkQuery = "SELECT * FROM uashotel WHERE no_kamar = ? or kode_kamar = ?";
        PreparedStatement checkStmt = conn.prepareStatement(checkQuery);
        checkStmt.setInt(1, nomor);
        checkStmt.setString(2, kode);
        ResultSet rs = checkStmt.executeQuery();

        if (rs.next()) {
            System.out.println("Kamar sudah dipesan!!!");
            return; // 
        }else{

        stmt = conn.createStatement();

        // Operasi db

        String sql = "INSERT INTO uashotel (kode_kamar,no_kamar,nama,jenis_kamar,harga) VALUES (?, ?, ?, ?, ?)";
        PreparedStatement ps = conn.prepareStatement(sql);
        ps.setString(1, kode);
        ps.setInt(2, nomor);
        ps.setString(3, nama);
        ps.setString(4, jenis);
        ps.setInt(5, harga);       
               
        
        int x = ps.executeUpdate();
        if (x==1)
        {
            JOptionPane.showMessageDialog(this,"Data Berhasil Ditambah");
            txtKode.setText("");
            txtNomor.setText("");
            txtNama.setText("");
            CBJenis.setSelectedItem("");            
            txtHarga.setText("0");            
            txtKode.requestFocus();
        }else
        {
            JOptionPane.showMessageDialog(this,"Data Gagal Ditambah");
        }
        }
        stmt.close();
        conn.close();
    } catch (Exception e) {
        
        e.printStackTrace();
    }
}     
    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> CBJenis;
    private javax.swing.JButton Delete;
    private javax.swing.JComboBox<String> NoKamar;
    private javax.swing.JButton Reset;
    private javax.swing.JButton Simpan;
    private javax.swing.JButton Update;
    private javax.swing.JButton View;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JMenu menuKeluar;
    private javax.swing.JTextField txtHarga;
    private javax.swing.JTextField txtKode;
    private javax.swing.JTextField txtNama;
    private javax.swing.JTextField txtNomor;
    // End of variables declaration//GEN-END:variables
}
