/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package UAS_PBO;

import java.sql.*;
import java.time.LocalDate;
import java.util.concurrent.TimeUnit;
import javax.swing.SwingUtilities;
import javax.swing.table.DefaultTableModel;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.text.ParseException;
import javax.swing.JOptionPane;

/**
 *
 * @author ASUS
 */
public class Transaksi extends javax.swing.JFrame {
    static final String JDBC_DRIVER = "com.mysql.cj.jdbc.Driver";
    static final String DB_URL = "jdbc:mysql://127.0.0.1/test";
    static final String USER = "root";
    static final String PASS = "";
    
    static Connection conn;
    static Statement stmt;
    static ResultSet rs;
   // Date tanggal = (Date) ;
    //DateFormat format = new SimpleDateFormat("dd/MM/yyyy");
    //String tanggalString = format.format(tanggal);


    /**
     * Creates new form Transaksi
     */
    public Transaksi() {
        initComponents();
        //showtable();
        //getData();
        //hitung();
        //tabelData.setEnabled(false); 
        Date currentDate = new Date(System.currentTimeMillis());
        dateMasuk.setDate(currentDate);
        dateKeluar.setDate(currentDate);
        txtHarga.setEditable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        tabelData = new javax.swing.JTable();
        Header = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtKode = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        dateMasuk = new com.toedter.calendar.JDateChooser();
        jLabel14 = new javax.swing.JLabel();
        dateKeluar = new com.toedter.calendar.JDateChooser();
        jLabel12 = new javax.swing.JLabel();
        CBJenis = new javax.swing.JComboBox<>();
        jLabel15 = new javax.swing.JLabel();
        txtHarga = new javax.swing.JTextField();
        Tambah = new javax.swing.JButton();
        Update = new javax.swing.JButton();
        Delete = new javax.swing.JButton();
        Reset = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuKeluar = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                formInputMethodTextChanged(evt);
            }
        });
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        tabelData.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID Kamar", "Jenis Kamar", "Harga", "Tanggal Masuk", "Tanggal Keluar"
            }
        ));
        tabelData.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelDataMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tabelData);

        Header.setText("Menu Transaksi");

        jLabel8.setText("ID Kamar");

        txtKode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtKodeActionPerformed(evt);
            }
        });

        jLabel13.setText("Tanggal Masuk");

        dateMasuk.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                dateMasukAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        dateMasuk.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dateMasukMouseClicked(evt);
            }
        });
        dateMasuk.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                dateMasukInputMethodTextChanged(evt);
            }
        });

        jLabel14.setText("Tanggal Keluar");

        dateKeluar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dateKeluarMouseClicked(evt);
            }
        });
        dateKeluar.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                dateKeluarInputMethodTextChanged(evt);
            }
        });
        dateKeluar.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                dateKeluarPropertyChange(evt);
            }
        });
        dateKeluar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                dateKeluarKeyPressed(evt);
            }
        });

        jLabel12.setText("Jenis Kamar");

        CBJenis.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Normal", "Deluxe", "Suite" }));
        CBJenis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CBJenisActionPerformed(evt);
            }
        });

        jLabel15.setText("Harga");

        txtHarga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtHargaActionPerformed(evt);
            }
        });

        Tambah.setText("Tambah");
        Tambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TambahActionPerformed(evt);
            }
        });

        Update.setText("Update");
        Update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateActionPerformed(evt);
            }
        });

        Delete.setText("Delete");
        Delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteActionPerformed(evt);
            }
        });

        Reset.setText("Reset");
        Reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ResetActionPerformed(evt);
            }
        });

        menuKeluar.setText("Keluar");
        menuKeluar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuKeluarMouseClicked(evt);
            }
        });
        menuKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuKeluarActionPerformed(evt);
            }
        });
        jMenuBar1.add(menuKeluar);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Tambah)
                        .addGap(18, 18, 18)
                        .addComponent(Update)
                        .addGap(18, 18, 18)
                        .addComponent(Delete)
                        .addGap(18, 18, 18)
                        .addComponent(Reset))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(CBJenis, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtHarga, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(dateKeluar, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel13)
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtKode, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(dateMasuk, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addComponent(Header, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 617, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(Header)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtKode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel13)
                    .addComponent(dateMasuk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel14)
                    .addComponent(dateKeluar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(CBJenis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(txtHarga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Tambah)
                    .addComponent(Update)
                    .addComponent(Delete)
                    .addComponent(Reset))
                .addContainerGap(61, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuKeluarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuKeluarMouseClicked
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_menuKeluarMouseClicked
    
    private void menuKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuKeluarActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_menuKeluarActionPerformed

    private void CBJenisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CBJenisActionPerformed
        // TODO add your handling code here:        
        hitung();
    }//GEN-LAST:event_CBJenisActionPerformed

    private void txtHargaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtHargaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtHargaActionPerformed

    private void txtKodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtKodeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtKodeActionPerformed

    private void tabelDataMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelDataMouseClicked
        // TODO add your handling code here:
        int baris = tabelData.getSelectedRow();    
        txtKode.setText(String.valueOf(tabelData.getValueAt(baris, 0)));
        CBJenis.setSelectedItem(String.valueOf(tabelData.getValueAt(baris, 1)));
        txtHarga.setText(String.valueOf(tabelData.getValueAt(baris, 2)));

        DateFormat format = new SimpleDateFormat("yyyy-MM-dd");
        try {
            java.util.Date tanggalMasukUtil = format.parse(String.valueOf(tabelData.getValueAt(baris, 3)));
            dateMasuk.setDate(tanggalMasukUtil);
        } catch (ParseException e) {
        }

        try {
            java.util.Date tanggalKeluarUtil = format.parse(String.valueOf(tabelData.getValueAt(baris, 4)));
            dateKeluar.setDate(tanggalKeluarUtil);
        } catch (ParseException e) {            
        }    


        
        //Tambah.setEnabled(false);
    }//GEN-LAST:event_tabelDataMouseClicked

    private void TambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TambahActionPerformed
        // TODO add your handling code here:
        new Hotel().setVisible(true);
    }//GEN-LAST:event_TambahActionPerformed

    private void UpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateActionPerformed
        // TODO add your handling code here:
       Date currentDate = new Date(System.currentTimeMillis());       
       try {
           String kode = txtKode.getText();                     
           String jenis = CBJenis.getSelectedItem().toString().trim();
           int harga = Integer.parseInt(txtHarga.getText().trim());
           Date tglMsk = new Date(dateMasuk.getDate().getTime());
           Date tglKlr = new Date(dateKeluar.getDate().getTime());
        Class.forName(JDBC_DRIVER);
        conn = DriverManager.getConnection(DB_URL, USER, PASS);     
        stmt = conn.createStatement();

        // Operasi db
        //String checkSql = "SELECT * FROM barang WHERE id = ?";
        String sql = "UPDATE uashotel set kode_kamar=?, jenis_kamar= ?, harga= ?, tgl_masuk = ?, tgl_keluar=? where kode_kamar=?";
        PreparedStatement ps = conn.prepareStatement(sql);
        //PreparedStatement psc = conn.prepareStatement(checkSql);
        //psc.setInt(1, id);        "UPDATE uashotel set kode_kamar=?, nama= ?, jenis = ?, tanggal_masuk = ?, tanggal_keluar=? WHERE no_kamar=?";
        ps.setString(1, kode);                
        ps.setString(2, jenis);
        ps.setInt(3, harga);
        ps.setDate(4, tglMsk);
        ps.setDate(5, tglKlr);
        ps.setString (6,kode);

        int x = ps.executeUpdate();
        
        if (x==1)
        {
            JOptionPane.showMessageDialog(this,"Data berhasil diupdate");
            txtKode.setText("");           
            CBJenis.setSelectedItem("");
            txtHarga.setText("");
            dateMasuk.setDate(currentDate);
            dateKeluar.setDate(currentDate);
            txtKode.requestFocus();
        }else
        {
            JOptionPane.showMessageDialog(this,"Data Gagal diupdate!");
        }
        

        stmt.close();
        conn.close();
    } catch (Exception e) {
    }
       showtable();
    }//GEN-LAST:event_UpdateActionPerformed

    private void DeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteActionPerformed
        // TODO add your handling code here:
        new Laporan().setVisible(true);
    }//GEN-LAST:event_DeleteActionPerformed

    private void ResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ResetActionPerformed
        // TODO add your handling code here:
        Tambah.setEnabled(true);
        txtKode.setText("");        
        CBJenis.setSelectedItem("");
        txtHarga.setText("0"); 
        showtable();
        
    }//GEN-LAST:event_ResetActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        showtable();
        hitung();        
    }//GEN-LAST:event_formWindowOpened

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:
        
    }//GEN-LAST:event_formWindowActivated

    private void formInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_formInputMethodTextChanged
        // TODO add your handling code here:
        
    }//GEN-LAST:event_formInputMethodTextChanged

    private void dateMasukMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dateMasukMouseClicked
        // TODO add your handling code here:
      
    }//GEN-LAST:event_dateMasukMouseClicked

    private void dateKeluarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dateKeluarMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_dateKeluarMouseClicked

    private void dateMasukAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_dateMasukAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_dateMasukAncestorAdded

    private void dateMasukInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_dateMasukInputMethodTextChanged
        // TODO add your handling code here:
        
    }//GEN-LAST:event_dateMasukInputMethodTextChanged

    private void dateKeluarInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_dateKeluarInputMethodTextChanged
        // TODO add your handling code here:
        
    }//GEN-LAST:event_dateKeluarInputMethodTextChanged

    private void dateKeluarPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_dateKeluarPropertyChange
        // TODO add your handling code here:        
    }//GEN-LAST:event_dateKeluarPropertyChange

    private void dateKeluarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_dateKeluarKeyPressed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_dateKeluarKeyPressed

    public void hitung()
    {
    int harga = 0;
        Date tglMsk = new Date(dateMasuk.getDate().getTime());
        Date tglKlr = new Date(dateKeluar.getDate().getTime());
        String selectedOption = (String) CBJenis.getSelectedItem();
                if (selectedOption.equals("Normal")) {
                    long selisihHari = TimeUnit.DAYS.convert(tglKlr.getTime() - tglMsk.getTime(), TimeUnit.MILLISECONDS);
                    harga = 500000*(int)selisihHari;
                } else if (selectedOption.equals("Deluxe")) {
                    long selisihHari = TimeUnit.DAYS.convert(tglKlr.getTime() - tglMsk.getTime(), TimeUnit.MILLISECONDS);
                    harga = 1000000*(int)selisihHari;
                } else if (selectedOption.equals("Suite")) {
                    long selisihHari = TimeUnit.DAYS.convert(tglKlr.getTime() - tglMsk.getTime(), TimeUnit.MILLISECONDS);
                    harga = 1500000*(int)selisihHari;
                }            
                txtHarga.setText(Integer.toString(harga));
    }
    public void showtable(){
        try{
            Class.forName(JDBC_DRIVER);	   
            conn = DriverManager.getConnection(DB_URL, USER, PASS);
            stmt = conn.createStatement();
            String sql = "SELECT * FROM uashotel";
            rs = stmt.executeQuery(sql);
            DefaultTableModel model = new DefaultTableModel();

            model.addColumn("ID Kamar");
            model.addColumn("Jenis Kamar");
            model.addColumn("Harga");
            model.addColumn("Tanggal Masuk");
            model.addColumn("Tanggal Keluar");
 
            while (rs.next()) {
                // Extract data from the result set
                String kode = rs.getString("kode_kamar");
                String jenis = rs.getString("jenis_kamar");
                int harga = rs.getInt("harga");
                Date tglMsk = rs.getDate("tgl_masuk");
                Date tglKlr = rs.getDate("tgl_keluar");

                // Add a new row to the table model
                model.addRow(new Object[]{kode, jenis, harga, tglMsk, tglKlr});
            }
            rs.close();
            conn.close();
            stmt.close();
            
            tabelData.setModel(model);
        }
        catch(Exception e){
        }
    }
      


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> CBJenis;
    private javax.swing.JButton Delete;
    private javax.swing.JLabel Header;
    private javax.swing.JButton Reset;
    private javax.swing.JButton Tambah;
    private javax.swing.JButton Update;
    private com.toedter.calendar.JDateChooser dateKeluar;
    private com.toedter.calendar.JDateChooser dateMasuk;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JMenu menuKeluar;
    private javax.swing.JTable tabelData;
    private javax.swing.JTextField txtHarga;
    private javax.swing.JTextField txtKode;
    // End of variables declaration//GEN-END:variables

}
