/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package UAS_PBO;
import static UAS_PBO.Hotel.DB_URL;
import static UAS_PBO.Hotel.JDBC_DRIVER;
import static UAS_PBO.Hotel.PASS;
import static UAS_PBO.Hotel.USER;
import static UAS_PBO.Hotel.conn;
import static UAS_PBO.Hotel.rs;
import static UAS_PBO.Hotel.stmt;
import javax.swing.JOptionPane;
import java.sql.*;

/**
 *
 * @author MUHAMMAD RAYHAN
 */
public class User extends javax.swing.JFrame {
    static final String JDBC_DRIVER = "com.mysql.cj.jdbc.Driver";
    static final String DB_URL = "jdbc:mysql://127.0.0.1/test";
    static final String USER = "root";
    static final String PASS = "";
    
    static Connection conn;
    static Statement stmt;
    static ResultSet rs;
    /**
     * Creates new form User
     */
    public User() {
        initComponents();
        pilihan();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        CBID = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        txtUser = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtPass = new javax.swing.JTextField();
        butTambah = new javax.swing.JButton();
        butUpdate = new javax.swing.JButton();
        butDelete = new javax.swing.JButton();
        butReset = new javax.swing.JButton();
        butView = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuKeluar = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("ID");

        jLabel2.setText("Username");

        jLabel3.setText("Password");

        butTambah.setText("Tambah");
        butTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butTambahActionPerformed(evt);
            }
        });

        butUpdate.setText("Update");
        butUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butUpdateActionPerformed(evt);
            }
        });

        butDelete.setText("Delete");
        butDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butDeleteActionPerformed(evt);
            }
        });

        butReset.setText("Reset");
        butReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butResetActionPerformed(evt);
            }
        });

        butView.setText("View");
        butView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butViewActionPerformed(evt);
            }
        });

        menuKeluar.setText("Keluar");
        menuKeluar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuKeluarMouseClicked(evt);
            }
        });
        menuKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuKeluarActionPerformed(evt);
            }
        });
        jMenuBar1.add(menuKeluar);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(90, 90, 90)
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(txtUser, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(butReset)))
                .addContainerGap(81, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(CBID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(butView))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(90, 90, 90)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtPass, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(butTambah)
                        .addGap(18, 18, 18)
                        .addComponent(butUpdate)
                        .addGap(18, 18, 18)
                        .addComponent(butDelete)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CBID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(butView))
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtPass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(butTambah)
                    .addComponent(butUpdate)
                    .addComponent(butDelete))
                .addGap(18, 18, 18)
                .addComponent(butReset)
                .addGap(46, 46, 46))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void butViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butViewActionPerformed
        // TODO add your handling code here:
        try {
    int id = Integer.parseInt(CBID.getSelectedItem().toString());
    conn = DriverManager.getConnection(DB_URL, USER, PASS);
    
    String sql = "SELECT * FROM user WHERE id = ?";
    PreparedStatement statement = conn.prepareStatement(sql);
    statement.setInt(1, id);
    
    ResultSet rs = statement.executeQuery();
    
    if (rs.next()) {
        txtUser.setText(rs.getString(2));
        txtPass.setText(rs.getString(3));
        
    }
     butTambah.setEnabled(false);
    conn.close();
} catch (SQLException e) {
    e.printStackTrace();
}
    }//GEN-LAST:event_butViewActionPerformed

    private void butTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butTambahActionPerformed
        // TODO add your handling code here:
        String user = txtUser.getText().toString().trim();
        String pass = txtPass.getText().toString().trim();
        int id = Integer.parseInt(CBID.getSelectedItem().toString());
        //insert(kode,nomor,nama,jenis,harga,tglMsk,tglKlr);
            Date currentDate = new Date(System.currentTimeMillis());
    try {
        Class.forName(JDBC_DRIVER);
        conn = DriverManager.getConnection(DB_URL, USER, PASS);

        // Pengecekan kd_brg
        String checkQuery = "SELECT * FROM user WHERE username = ?";
        PreparedStatement checkStmt = conn.prepareStatement(checkQuery);        
        checkStmt.setString(1, user);        
        ResultSet rs = checkStmt.executeQuery();

        if (rs.next()) {           
            String userFromDB = rs.getString("username");            
            if (user.equals(userFromDB)) {
                JOptionPane.showMessageDialog(this,"Username sudah ada, silahkan ganti dengan yang lain.");
                return;        
            }
        }else {
        

        stmt = conn.createStatement();

        // Operasi db

        String sql = "INSERT INTO user (username,password) VALUES (?, ?)";
        PreparedStatement ps = conn.prepareStatement(sql);
        ps.setString(1, user);
        ps.setString(2, pass);
                               
        int x = ps.executeUpdate();
        if (x==1)
        {
            JOptionPane.showMessageDialog(this,"Data Berhasil Ditambah");
            txtUser.setText("");
            txtPass.setText("");
            
        }else
        {
            JOptionPane.showMessageDialog(this,"Data Gagal Ditambah");
        }
        }
        
        stmt.close();
        conn.close();
    } catch (Exception e) {
        
        e.printStackTrace();
    }
    }//GEN-LAST:event_butTambahActionPerformed

    private void butUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butUpdateActionPerformed
        // TODO add your handling code here:         
       int id = Integer.parseInt(CBID.getSelectedItem().toString());
       try {
           String user = txtUser.getText();           
           String pass = txtPass.getText();           
        Class.forName(JDBC_DRIVER);
        conn = DriverManager.getConnection(DB_URL, USER, PASS);     
        stmt = conn.createStatement();

        // Operasi db
        //String checkSql = "SELECT * FROM barang WHERE id = ?";
        String sql = "UPDATE user set username=?, password= ? WHERE id =?";
        PreparedStatement ps = conn.prepareStatement(sql);
        //PreparedStatement psc = conn.prepareStatement(checkSql);
        //psc.setInt(1, id);        "UPDATE uashotel set kode_kamar=?, nama= ?, jenis = ?, tanggal_masuk = ?, tanggal_keluar=? WHERE no_kamar=?";
        ps.setString(1, user);
        ps.setString(2, pass);
        ps.setInt(3, id);        

        int x = ps.executeUpdate();
        
        if (x==1)
        {
            JOptionPane.showMessageDialog(this,"Data berhasil diupdate");
            txtUser.setText("");
            txtPass.setText("");            
            txtUser.requestFocus();
        }else
        {
            JOptionPane.showMessageDialog(this,"Data Gagal diupdate!");
        }
        

        stmt.close();
        conn.close();
    } catch (Exception e) {
        e.printStackTrace();
    }
    }//GEN-LAST:event_butUpdateActionPerformed

    private void butDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butDeleteActionPerformed
        // TODO add your handling code here:       
       int id = Integer.parseInt(CBID.getSelectedItem().toString());           
       try {        
        Class.forName(JDBC_DRIVER);
        conn = DriverManager.getConnection(DB_URL, USER, PASS);     
        stmt = conn.createStatement();

        // Operasi db
        //String checkSql = "SELECT * FROM barang WHERE id = ?";
        String sql = "Delete from user where id=?";
        PreparedStatement ps = conn.prepareStatement(sql);
        //PreparedStatement psc = conn.prepareStatement(checkSql);
        //psc.setInt(1, id);                
        ps.setInt(1,id );

        int x = ps.executeUpdate();
        
        if (x==1)
        {
            JOptionPane.showMessageDialog(this,"Data Berhasil Dihapus");
            txtUser.setText("");
            txtPass.setText("");            
            txtUser.requestFocus();
        }else
        {
            JOptionPane.showMessageDialog(this,"Data Gagal Dihapus");
        }
        stmt.close();
        conn.close();
    } catch (Exception e) {        
        e.printStackTrace();
    }
    }//GEN-LAST:event_butDeleteActionPerformed

    private void butResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butResetActionPerformed
        // TODO add your handling code here:             
        butTambah.setEnabled(true);
        txtUser.setText("");
        txtPass.setText("");        
        CBID.setSelectedIndex(0);
    }//GEN-LAST:event_butResetActionPerformed

    private void menuKeluarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuKeluarMouseClicked
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_menuKeluarMouseClicked

    private void menuKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuKeluarActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_menuKeluarActionPerformed

    private void pilihan()
    {
        try {
            conn = DriverManager.getConnection(DB_URL, USER, PASS);
            stmt = conn.createStatement();
            rs = stmt.executeQuery("SELECT id FROM user");
            while(rs.next())
            {
                CBID.addItem(rs.getString(1).toString());
            }
            
            stmt.close();
            conn.close();
            rs.close();
        } catch (SQLException e) {
            e.printStackTrace();
            
        }
    }
    /**
     * @param args the command line arguments
     */   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> CBID;
    private javax.swing.JButton butDelete;
    private javax.swing.JButton butReset;
    private javax.swing.JButton butTambah;
    private javax.swing.JButton butUpdate;
    private javax.swing.JButton butView;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu menuKeluar;
    private javax.swing.JTextField txtPass;
    private javax.swing.JTextField txtUser;
    // End of variables declaration//GEN-END:variables
}
